kind: Deployment
apiVersion: apps/v1
metadata:
  name: lrds
spec:
    replicas: 3
    selector:
        matchLabels:
            app: lrds
    template:
        metadata:
            labels:
                app: lrds
        spec:
            containers:
            - name: lrds
              image: alexlauni/liftright-data-server:191f73b
              env:
              - name: MONGO_DATABASE_CONN
                valueFrom:
                    secretKeyRef:
                        name: lrds-db-conn
                        key: mongo
              - name: RUST_LOG
                value: liftright_data_server=debug,warp=debug
---
kind: Service
apiVersion: v1
metadata:
    name: lrds
spec:
    selector:
        app: lrds
    ports:
    - port: 3030
