kind: Pod
apiVersion: v1
metadata:
  name: lrds-app
  labels:
      app: lrds
spec:
    containers:
    - name: liftright-data-server
      image: localhost:5000/lrds:0b0b9ea
      env:
      - name: MONGO_DATABASE_CONN
        value: mongodb://lrds:58LObjiMpxcjP1sMDW@mongodb-svc.default.svc.cluster.local/liftright-dev?replicaSet=mongodb&authMechanism=SCRAM-SHA-256
      - name: RUST_LOG
        value: liftright_data_server=debug,warp=debug
---
kind: Service
apiVersion: v1
metadata:
    name: lrds-service
spec:
    selector:
        app: lrds
    ports:
    - port: 3030
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
    name: lrds-ingress
spec:
    rules:
    - http:
        paths:
        - path: /
          backend:
              serviceName: lrds-service
              servicePort: 3030
---
