kind: Deployment
apiVersion: apps/v1
metadata:
  name: lrds
spec:
    replicas: 3
    selector:
        matchLabels:
            app: lrds
    template:
        metadata:
            labels:
                app: lrds
        spec:
            containers:
            - name: lrds
              image: alexlauni/liftright-data-server:77eef84
              env:
              - name: MONGO_DATABASE_CONN
                valueFrom:
                    secretKeyRef:
                        name: lrds-db-conn
                        key: mongo
              - name: RUST_LOG
                value: liftright_data_server=debug,warp=debug
---
kind: Service
apiVersion: v1
metadata:
    name: lrds
spec:
    selector:
        app: lrds
    ports:
    - port: 3030
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
    name: lrds-ingress
spec:
    rules:
    - host: staging.liftright.dirigim.lan
      http:
        paths:
        - path: /
          backend:
              serviceName: lrds
              servicePort: 3030
---
            

