apiVersion: v1
kind: ServiceAccount
metadata:
  name: lrds
---
apiVersion: v1
kind: Service
metadata:
  name: lrds
  labels:
    app: lrds
spec:
  ports:
    - port: 80
      targetPort: 3030
      name: http
  selector:
    app: lrds
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lrds-v1
  labels:
    app: lrds
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lrds
      version: v1
  template:
    metadata:
      labels:
        app: lrds
        version: v1
    spec:
      containers:
        - name: lrds
          image: alexlauni/liftright-data-server:191f73b
          imagePullPolicy: IfNotPresent
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 60
            httpGet:
              path: /v1/rtfb_status/6fcd683c-20d5-415d-a134-1e7d2f780749
              port: 3030
              scheme: HTTP
            timeoutSeconds: 3
            failureThreshold: 5
            successThreshold: 1
          livenessProbe:
            initialDelaySeconds: 1
            periodSeconds: 60
            httpGet:
              path: /v1/heartbeat
              port: 3030
              scheme: HTTP
            timeoutSeconds: 1
            failureThreshold: 1
            successThreshold: 1
          env:
            - name: MONGO_DATABASE_CONN
              valueFrom:
                secretKeyRef:
                  name: lrds-db-conn
                  key: mongo
            - name: RUST_LOG
              value: "liftright_data_server=debug;warp=debug"
          ports:
            - containerPort: 3030
