apiVersion: apps/v1
kind: Deployment
metadata:
  name: lrds
  namespace: lrds
  labels:
    app: lrds
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lrds
  template:
    metadata:
      labels:
        app: lrds
    spec:
      containers:
        - name: lrds
          image: alexlauni/liftright-data-server:191f73b
          env:
            - name: MONGO_DATABASE_CONN
              valueFrom:
                secretKeyRef:
                  name: lrds-db-conn
                  key: mongo
            - name: RUST_LOG
              value: liftright_data_server=debug,warp=debug
