apiVersion: v1
kind: Service
metadata:
    name: lrds
    namespace: lrds
    labels:
        app: lrds
spec:
    type: ClusterIP
    selector:
        app: lrds
    ports:
    - name: http
      port: 3030
      protocol: TCP
      targetPort: http
