apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: lrds-db-conn
  namespace: default
spec:
  encryptedData:
    mongo: AgCEbw73KuVFrGUXGdocyMduze4osPZpPwZpuSuP+X+NnzbnS8nu2/8IdSII6+mGgNg0bP03kARDVRc1dEM8YKQUAxYed0lFxncYeZrkgQRuENvbCWpaJNtPFIAkVxdtaDC8yzCli4yJ3ozPdCiP4tlMLpsITTyczeUD3KVqnKX6fPUdsMNqX048mUmspU1PaTczD1+3G981yRTKYU98/DToDRZ9lU4BDjzKCmmzcWAiXZnvrgKKGFVz8RphVMwCLHbsdXm85aNVooTK0hCXBGUcz3XOMQjQidQo+wCc3NA+z4Kck4GPGp4OpJPy9JYW+xstfUIxnzc81HyXG7LJm9jQm33ktJNwTzrmKlxyl9PJ2bVaz9ur1cT87HFSFPjn/KMDx68Gu0QQ5ajCmXvmS28DM4xJDj6CxvHVGtLzibHRhHiJaO++1/OrkAcL8L6m96n29oeL8Ce+iAlSfcUbIG1ts9hSpmaLZQ4f3DVeNe95vCmq+bicjnrjf46Eyg6aWhiO3iBDO5wyid2xethnfGSDQ8aU5iVatAsaOz9nXyjJixsqtZQi8UQUpGRdimB4rpBd5uQF29OQ9keqXZR2QyjmOvHZA3ME+9y7MUXG2oxKZgmOjT59E6bvvRe1gpJ4bFjkgEjeq9dNK+rrOId6+f5iI4au5qeOCq5BYOOJLFMZoo1xphU7oLWs8EkNDesQIsQ9O6ZOZbtZzpH4mDJTDpCoqLusP4+xFsaUWPm1aSCV8W9BaV+ybE7nsLo3U59lmZ/0On4jcyItNKC8qTf4s0rL/ZfOEP6q7lP6I2vMhJQze7u2GicxgHJReg==
  template:
    metadata:
      creationTimestamp: null
      name: lrds-db-conn
      namespace: default

