apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lrds
spec:
  hosts:
  - "staging.liftright.dirigim.us"
  gateways:
  - lrds-gateway
  http:
  - match:
    - uri:
        prefix: /v1
    route:
    - destination:
        port:
          number: 80
        host: lrds
