---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: liftright-staging
  namespace: istio-system
spec:
  secretName: letsencrypt-staging
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: staging.liftright.dirigim.us
  dnsNames:
    - staging.liftright.dirigim.us
